
# DNS Records the the important entry-points in the stack. 
# Each entry embeds the shared DNSPrefix parameter, to allow multiple deploys.
#
#    logs.<prefix>.lcip.org:     log collection server
#    api-accounts.<prefix>.lcip.org:      loadbalancer fronting webheads
#    scrypt-accounts.<prefix>.lcip.org:   loadbalancer fronting scrypt nodes
#    db.<prefix>.lcip.org:       public alias for the MySQL database
#    redis.<prefix>.lcip.org:    public alias for the Redis database

DNSRecords:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneName: "lcip.org."
    RecordSets:
      - Name: {"Fn::Join": [".", ["logs", {"Ref": "DNSPrefix"}, "lcip.org."]]}
        Type: CNAME
        TTL: "30"
        ResourceRecords:
          - {"Fn::GetAtt": ["LogServer", "PublicDnsName"]}
      - Name: {"Fn::Join": [".", ["api-accounts", {"Ref":"DNSPrefix"}, "lcip.org."]]}
        Type: CNAME
        TTL: "30"
        ResourceRecords:
          - {"Fn::GetAtt": ["IdpLoadBalancer", "DNSName"]}
      - Name: {"Fn::Join": [".", ["db", {"Ref":"DNSPrefix"}, "lcip.org."]]}
        Type: CNAME
        TTL: "30"
        ResourceRecords:
          - {"Fn::GetAtt": ["Database", "Endpoint.Address"]}
      - Name: {"Fn::Join": [".", ["scrypt-accounts", {"Ref":"DNSPrefix"}, "lcip.org."]]}
        Type: CNAME
        TTL: "30"
        ResourceRecords:
          - {"Fn::GetAtt": ["ScryptLoadBalancer", "DNSName"]}
      - Name: {"Fn::Join": [".", ["redis", {"Ref": "DNSPrefix"}, "lcip.org."]]}
        Type: CNAME
        TTL: "30"
        ResourceRecords:
          - {"Fn::GetAtt": ["RedisServer", "PublicDnsName"]}


# The log-collecting server, and associated infra.
# It's just a stand-alone box.

LogServer:
  Type: AWS::EC2::Instance
  Properties:
    # This needs a hekuva lotta CPU to keep up with all the logs...
    InstanceType: m1.xlarge
    ImageId: { "Ref": "LogBoxAMI" }
    KeyName: { "Ref": "AWSBoxDeployKey" }
    SecurityGroups:
      - {"Ref": "LogServerSecurityGroup"}
    BlockDeviceMappings:
      - DeviceName: "/dev/sdb"
        VirtualName: "ephemeral0"
    UserData: {"Fn::Base64": {"Fn::Join": ["", [
      "#!/bin/bash\n",
      "set -e -x\n",
      # Symlink ephemeral storage onto /var/data, preserving contents.
      "tar -cjvf /tmp/datadir.tar.bz2 /var/data/elasticsearch\n",
      "rm -rf /var/data\n",
      "ln -s /media/ephemeral0 /var/data\n",
      "tar -xjvf /tmp/datadir.tar.bz2 -C /\n",
      "rm /tmp/datadir.tar.bz2\n",
      # Execute local startup after cloudinit has run.
      "mv /etc/rc.local.post-cloudinit /etc/rc.local\n",
      "exec /etc/rc.local\n",
       ]]}}


LogServerSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "awsboxen security group for log-collecting server"
    SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        CidrIp: "0.0.0.0/0"
      # Allow inbound web traffic from anywhere.
      - IpProtocol: "tcp"
        FromPort: "80"
        ToPort: "80"
        CidrIp: "0.0.0.0/0"
      - IpProtocol: "tcp"
        FromPort: "443"
        ToPort: "443"
        CidrIp: "0.0.0.0/0"
      # Allow ElasticSearch access, for the  kibana web interface.
      - IpProtocol: "tcp"
        FromPort: "9200"
        ToPort: "9200"
        CidrIp: "0.0.0.0/0"
      # Allow access to heka web dashboard.
      - IpProtocol: "tcp"
        FromPort: "4352"
        ToPort: "4352"
        CidrIp: "0.0.0.0/0"
      # Allow inbound heka logs from the other resources in this stack.
      # XXX TODO: lock down these ports a little more...
      - IpProtocol: "tcp"
        FromPort: "5000"
        ToPort: "12000"
        SourceSecurityGroupName: {"Ref": "HekaClientSecurityGroup"}


HekaClientSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "awsboxen security group for heka clients"


# The fxa-auth-server webheads, and associated infra.
# These machines are stateless, so we run an auto-scaling group of them

IdpLoadBalancer:
  Type: AWS::ElasticLoadBalancing::LoadBalancer
  Properties:
    AvailabilityZones: {"Fn::GetAZs": ""}
    Listeners:
      - LoadBalancerPort: "80"
        InstancePort: "80"
        Protocol: "HTTP"
    HealthCheck:
      Target: "HTTP:80/__heartbeat__"
      HealthyThreshold: "2"
      UnhealthyThreshold: "2"
      Interval: "10"
      Timeout: "5"


IdpAutoScaleGroup:
  Type: AWS::AutoScaling::AutoScalingGroup
  Properties:
    AvailabilityZones: { "Fn::GetAZs": ""}
    LaunchConfigurationName: { "Ref": "IdpServerLaunchConfig" }
    DesiredCapacity: "10"
    MinSize: "10"
    MaxSize: "10"
    LoadBalancerNames:
      - {"Ref": "IdpLoadBalancer"}
  DependsOn:
    - RedisServer
    - Database
  UpdatePolicy:
    AutoScalingRollingUpdate:
      MinInstancesInService: "1"
      MaxBatchSize: "1"


IdpServerLaunchConfig:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    InstanceType: c1.medium
    ImageId: { "Ref": "IdpBoxAMI" }
    KeyName: { "Ref": "AWSBoxDeployKey" }
    SecurityGroups:
      - {"Ref": "IdpServerSecurityGroup"}
      - {"Ref": "HekaClientSecurityGroup"}
    # Cause it to process cloud-init metadata on first run.
    UserData: {"Fn::Base64": {"Fn::Join": ["", [
      "#!/bin/bash\n",
      "set -e -x\n",
      "/opt/aws/bin/cfn-init --region ", {"Ref": "AWS::Region"}, " --stack ", {"Ref": "AWS::StackId"}, " --resource IdpServerLaunchConfig\n",
      "mv /etc/rc.local.post-cloudinit /etc/rc.local\n",
      "exec /etc/rc.local\n",
       ]]}}
  Metadata:
    AWS::CloudFormation::Init:
     config:
       files:
         # This is the .json config file in which the server will look
         # for customizations.  We write it at deploy time because it
         # needs to embed e.g. the public-facing URL, cache server URL, etc.
         /home/app/fxa-auth-server/config/cloud_formation.json:
           content:
             # Public-facing URL, as configured in the DNSRecord.
             publicUrl: {"Fn::Join": ["", ["http://", {"Fn::Join": [".", ["api-accounts", {"Ref": "DNSPrefix"}, "lcip.org"]]}]]}
             # Using the RDS MySQL instance for storage
             mysql:
               master:
                 user: "fxa"
                 password: {"Ref": "DBPassword"}
                 database: "fxa"
                 host: {"Fn::Join": [".", ["db",{"Ref":"DNSPrefix"},"lcip.org"]]}
               slave:
                 user: "fxa"
                 password: {"Ref": "DBPassword"}
                 database: "fxa"
                 host: {"Fn::Join": [".", ["db",{"Ref":"DNSPrefix"},"lcip.org"]]}
             # Using the Redis instance for nonce  cache
             redis:
               host: {"Fn::Join": [".", ["redis",{"Ref":"DNSPrefix"},"lcip.org"]]}
               password: {"Ref": "RedisPassword"}


IdpServerSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "awsboxen security group for fxa-auth-server webheads"
    SecurityGroupIngress:
      # Allow ssh from anywhere.
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        CidrIp: "0.0.0.0/0"
      # Allow access to heka web dashboard.
      - IpProtocol: "tcp"
        FromPort: "4352"
        ToPort: "4352"
        CidrIp: "0.0.0.0/0"


IdpSecurityGroupIngressForLoadBalancer:
  # Allow port 80 ingress from the load balancer.
  # This has to be a separate resource to avoid circular references
  # between IdpLoadBalancer and IdpServerLaunchConfig.
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    GroupName: {"Ref": "IdpServerSecurityGroup"}
    IpProtocol: "tcp"
    FromPort: "80"
    ToPort: "80"
    SourceSecurityGroupOwnerId: {"Fn::GetAtt": ["IdpLoadBalancer", "SourceSecurityGroup.OwnerAlias"]}
    SourceSecurityGroupName: {"Fn::GetAtt": ["IdpLoadBalancer", "SourceSecurityGroup.GroupName"]}


# The scrypt-helper webheads, and associated infra.
# These machines are stateless, so we run an auto-scaling group of them

ScryptLoadBalancer:
  Type: AWS::ElasticLoadBalancing::LoadBalancer
  Properties:
    AvailabilityZones: {"Fn::GetAZs": ""}
    Listeners:
      - LoadBalancerPort: "80"
        InstancePort: "80"
        Protocol: "HTTP"
    HealthCheck:
      Target: "TCP:80"
      HealthyThreshold: "2"
      UnhealthyThreshold: "2"
      Interval: "10"
      Timeout: "5"


ScryptAutoScaleGroup:
  Type: AWS::AutoScaling::AutoScalingGroup
  Properties:
    AvailabilityZones: { "Fn::GetAZs": ""}
    LaunchConfigurationName: { "Ref": "ScryptServerLaunchConfig" }
    DesiredCapacity: "5"
    MinSize: "5"
    MaxSize: "5"
    LoadBalancerNames:
      - {"Ref": "ScryptLoadBalancer"}
  UpdatePolicy:
    AutoScalingRollingUpdate:
      MinInstancesInService: "1"
      MaxBatchSize: "1"


ScryptServerLaunchConfig:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    InstanceType: m1.large
    ImageId: { "Ref": "ScryptBoxAMI" }
    KeyName: { "Ref": "AWSBoxDeployKey" }
    SecurityGroups:
      - {"Ref": "ScryptServerSecurityGroup"}
      - {"Ref": "HekaClientSecurityGroup"}
    UserData: {"Fn::Base64": {"Fn::Join": ["", [
      "#!/bin/bash\n",
      "set -e -x\n",
      "mv /etc/rc.local.post-cloudinit /etc/rc.local\n",
      "exec /etc/rc.local\n",
       ]]}}


ScryptServerSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "awsboxen security group for scrypt-helper webheads"
    SecurityGroupIngress:
      # Allow ssh from anywhere.
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        CidrIp: "0.0.0.0/0"
      # Allow access to heka web dashboard.
      - IpProtocol: "tcp"
        FromPort: "4352"
        ToPort: "4352"
        CidrIp: "0.0.0.0/0"


ScryptSecurityGroupIngressForLoadBalancer:
  # Allow port 80 ingress from the load balancer.
  # This has to be a separate resource to avoid circular references.
  Type: AWS::EC2::SecurityGroupIngress
  Properties:
    GroupName: {"Ref": "ScryptServerSecurityGroup"}
    IpProtocol: "tcp"
    FromPort: "80"
    ToPort: "80"
    SourceSecurityGroupOwnerId: {"Fn::GetAtt": ["ScryptLoadBalancer", "SourceSecurityGroup.OwnerAlias"]}
    SourceSecurityGroupName: {"Fn::GetAtt": ["ScryptLoadBalancer", "SourceSecurityGroup.GroupName"]}



# A redis instance for storing nonces.
# We'll probably grow into using redis for other things as well, so
# maybe it should probably be some sort of cluster...
# We could use ElastiCache for this, but it requires calling the AWS API
# at boot to determine the endpoing URL of the server.  Ugh.

RedisServer:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: c1.medium
    ImageId: { "Ref": "RedisBoxAMI" }
    KeyName: { "Ref": "AWSBoxDeployKey" }
    SecurityGroups:
      - {"Ref": "RedisServerSecurityGroup"}
      - {"Ref": "HekaClientSecurityGroup"}
    UserData: {"Fn::Base64": {"Fn::Join": ["", [
      "#!/bin/bash\n",
      "set -e -x\n",
      "mv /etc/rc.local.post-cloudinit /etc/rc.local\n",
      "exec /etc/rc.local\n",
       ]]}}


RedisServerSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: "awsboxen security group for redis server"
    SecurityGroupIngress:
      # Allow ssh from anywhere.
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        CidrIp: "0.0.0.0/0"
      # Allow redis protocol access from the webheads.
      - IpProtocol: "tcp"
        FromPort: "6379"
        ToPort: "6379"
        SourceSecurityGroupName: {"Ref": "IdpServerSecurityGroup"}


# The backend database, and supporting infra.
# This is a simple RDS MySQL instance.

Database:
  Type: AWS::RDS::DBInstance
  Properties:
    DBName: "fxa"
    Engine: "MySQL"
    Port: "3306"
    MasterUsername: "fxa"
    MasterUserPassword: {"Ref": "DBPassword"}
    DBInstanceClass: "db.m1.xlarge"
    AllocatedStorage: "20"
    MultiAZ: true
    DBSecurityGroups:
      - {"Ref": "DatabaseSecurityGroup"}


DatabaseSecurityGroup:
  Type: AWS::RDS::DBSecurityGroup
  Properties:
    GroupDescription: "awsboxen security group for fxa-auth-server database"
    DBSecurityGroupIngress:
        - EC2SecurityGroupName: {"Ref": "IdpServerSecurityGroup"}

